version: 0.0.4

services:

  couchdb:
    image: treehouses/couchdb:2.3.0
    restart: always
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-password}
    ports:
      - 5984:5984
    volumes:
      - couchdb_data:/opt/couchdb/data

  backend:
    build:
      context: backend
      target: builder
    restart: always
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-password}
      - GIN_MODE=release
    ports:
      - 8080:9000
    depends_on:
      - couchdb

  listener:
    build:
      context: listener
      target: builder
    restart: always
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-password}
      - MQTT_URL=${MQTT_URL:-example.com}
      - MQTT_USER=${MQTT_USER:-user}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-password}
    depends_on:
      - couchdb

  listener2:
    build:
      context: listener
      target: builder
    restart: always
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-password}
      - MQTT_URL=${MQTT_URL:-example.com}
      - MQTT_USER=${MQTT_SECOND_USER:-user}
      - MQTT_PASSWORD=${MQTT_SECOND_PASSWORD:-password}
    depends_on:
      - couchdb      

volumes:
  couchdb_data:
    driver: local